library(readr)
wages = read.csv("/home/juanmange/Documentos/Wages1.csv")
head(wages)
attach(wages)
wages$sex = factor(wages$sex, levels = c(0,1), labels = c("Mujer", "Hombre"))
head(wages)
boxplot(exper~sex, xlab="Sexo", ylab="Experiencia (años)", names=c("Mujer", "Hombre"), main="Experiencia según el sexo")
boxplot(school~sex, xlab="Sexo", ylab="Escolaridad (años)", names=c("Mujer", "Hombre"), main="Escolaridad según el sexo")
boxplot(wage~sex, xlab="Sexo", ylab="Salario (USD por hora)", names=c("Mujer", "Hombre"), main="Salario según el sexo")
library(PASWR2)
eda(wage)
eda(wage[sex==0])
eda(wage[sex==1])
library(dplyr)
wages %>% group_by(sex) %>% summarise(mean(exper), mean(school), mean(wage),median(exper), median(school), median(wage), sd(exper), sd(school), sd(wage))
lapply(split(wages$exper,wages$sex),shapiro.test)
lapply(split(wages$school,wages$sex),shapiro.test)
lapply(split(wages$wage,wages$sex),shapiro.test)
library(psych)
describe(wages)
# prueba de dos colas
t.test(wage, mu=5.76)
t.test(wage, mu=7)
# prueba de cola derecha
t.test(wage, mu=7, alternative = "greater")
#prueba de cola izquierda
t.test(wage, mu=7, alternative = "less")
library(psych)
describe(wages)
